name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 11.5
          - 11.6
          - 12
          - 12.4

    steps:
    - uses: actions/checkout@master
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Run unit tests with iPhone 11
      run:  xcodebuild clean test -project StoreTransitions.xcodeproj -scheme StoreTransitions -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty && exit ${PIPESTATUS[0]}
